### ISSUE TITLE
Crash with nvim (io.popen)

### ISSUE THREAD

**Issue by Dardanos-Aeolus** [k-lar/dynomark#2] opened 2024-09-17 19:30 UTC
Hi there.

This plugin looks great!
I had been looking for something like this for quite a while.

Do I understand correctly that at the moment it is expected, that this plugin is run under linux?

In the environment I want to use this most, I won't have the ability to install a GO compiler.

How much work would it be to support Windows via pre-built binaries?

**Comment by k-lar** [comment] 2024-09-19 08:47
The engine should be completely system agnostic, but I understand that it's a pain to have to install the Go toolchain to use it right now. I will 100% support pre-built binaries for all systems as soon as possible, I just want to get to a stable enough state where I feel comfortable offering them. The only 2 issues currently blocking this are minor issues with deeply nested files not getting queried correctly and me wanting to add `ORDER BY` or `SORT` functionality.
**At minimum** I want to fix the deeply nested files problem, then I can get some pre-release binaries out.

The plan going forward is:
1. ~~Fix deeply nested files not getting queried~~
2. ~~Make a pre-release so that people can get up and running quicker with binaries~~
3. Automatically download the engine through dynomark.nvim and eventually other editor plugins
4. Try adding `ORDER BY` or `SORT`
5. ~~Eventually get a proper 0.1.0 release~~
6. Develop plugins for other editors (or hopefully someone else does that because I have no idea how to do plugin development for VSCode or Emacs)

**Comment by k-lar** [comment] 2024-10-08 22:52
Finally we have an actual release! I ironed out all the smaller problems that were bugging me and it's definitely not done yet but it's usable.

You can find the Windows executable here: https://github.com/k-lar/dynomark/releases/tag/0.1.0

Do note that I haven't done any testing with Windows at all, but in theory it should work just fine. Just make sure that you add it to your PATH environment variable.

If you run into any problems, comment here or open another issue. The VSCode plugin is going to be published sometime this week. That will probably attract even more Windows users and I hope they'll let me know if there are more Windows specific problems.

**Comment by Dardanos-Aeolus** [comment] 2024-10-10 09:58
That's amazing.
Thank you.

Unfortunaltely I get this error:
```
```dynomark
LIST from templates/
\```
```
templates is a subdirectory of my current neovim PWD

Dynomark run:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0xe83ef2]

goroutine 1 [running]:
main.main()
	/home/klar/git/dynomark/main.go:1161 +0x2b2
```

**Comment by k-lar** [comment] 2024-10-10 14:40
That's really strange...
I sometimes got the program to hang when I was testing queries, but I don't think I ever got a panic before.

1. Are you running the newest 0.1.1 release?
2. Does running the same query work with just dynomark's CLI? You can check that by running `dynomark --query "LIST FROM templates/"` in the same directory where your markdown file with the query resides.

**Comment by Dardanos-Aeolus** [comment] 2024-10-11 08:02
It seems to be related to io.popen not working as expected on my Windows.

When I change the function execute_dynomark_query(query) to

‘’’
local result = vim.fn.system(“dynomark --query “ …)
‘’’
Then it works as expected.

**Comment by k-lar** [comment] 2024-10-11 08:37
I was able to reproduce this error on my Windows machine as well. Honestly I have no idea why this happens but I don't think it's a problem with the engine itself but with nvim's handling of `io.popen()` on Windows. `vim.fn.system()` does fix it, but I don't like it because it's blocking.

For now I'll push a fix to [dynomark.nvim](https://github.com/k-lar/dynomark.nvim) that checks if it's running on Windows and based on that it's going to decide to use either `io.popen()` or `vim.fn.system()`. When I'll have the time (or if someone wants to do a PR) I'll look into using `vim.fn.jobstart()` for all systems. I'll close this issue for now because from what I can see, this was a problem with [dynomark.nvim](https://github.com/k-lar/dynomark.nvim). If you have any more problems, please open an issue on that repo.

Thank you for bringing this issue up in the first place :)

**Closed as completed by k-lar** 2024-10-11 08:37 UTC
